language: java
script:
  - cd server
  - mvn clean compile
  - zip mortgage-tool.zip -r src pom.xml Procfile Buildfile
#deploy:
#  provider: elasticbeanstalk
#  access_key_id:
#    secure: "Encrypted <access-key-id>="
#  secret_access_key:
#    secure: "Encypted <secret-access-key>="
#  region: "eu-west-2"
#  app: "mortgage-tool"
#  env: "Mortgagetool-env-1"
#  bucket_name: "mortgage-tool-source"
#  zip_file: server/mortgage-tool.zip