language: java
script:
- mvn assembly:assembly -DdescriptorId=jar-with-dependencies -DskipTests
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region eu-west-2)
  - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y4b5m7t6
  - docker build -t mortgage-api .
  - docker tag mortgage-api:latest public.ecr.aws/y4b5m7t6/mortgage-api:latest
  - docker push public.ecr.aws/y4b5m7t6/mortgage-api:latest