language: java
script:
  - cd server
  - mvn clean compile
  - zip mortgage-tool.zip -r src pom.xml Procfile Buildfile
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "bqsus2OetNB9LoK2iYkNKMEaH7N2Nr+V087ottn7HQ2EKerXGXpfeRk4z0nIP6gYr4O/qRuzUt62P7qw5JV+Inq/OWMn/oN9op4vPAJmyXb5tWdNufcaGArleI3AgIFI0WR22OICvXlsKCARFJl7SmypfvSH6inQQbbSdnN+1zH5iu0TjmCzRtk19Z7pA/Bob0oiKK/JjRqqoQ8047QePpXV5vAjITK7f8PVcjFWTQ1WJC7CGmOS3PcPPFgGRZQhjnf4GryWvAJwDnS93uSJa8AjWw3TPEVa7rTAqSG79mM5Kw+dM5IUG4GmeyPLnnkgPRTfX00B8aFKMX2SvT92c13wsFcN6p6v/LzihNijshiKMYdGYXTO3WTB/JFIkt05B/6IwCbhfbtuvrJmwtAvZOLxs1HQ/9tksAKX2NTuNvD2zt8Q8B8yiRfqegvqivhRPix0x4wvU0B6AKQ0t7jfEqCYcP7cuJQmzquaeKigmZT3MiS+duQRnQsSuoM6eAwXsv3Vgc+BIXwI7/rDcGUNxahFiEnQqGOBynn8mBk3ZrkUnKYdHDwbS4kzUjJH+h2UTzSwlAMaX2ZXps2vt9KLdaqeD3FDepFJjzOf2AjO/23bHYVl6HW7hBVfGw6j53pbZ+8DHGrZ9pEHfvBcsVvM/wWNxXF95/NqKLbekx8bd7s="
  secret_access_key:
    secure: "GV3DjdntGVlDmLzy9P/06MLvrkmFAxPg6V8ui5GOyHVv7+HuVMMmiC/l6IwCTIerGBMPmRh89r6xuxXTeKG4gAFGj1PlotSZGZF0ccIpCYvpZhFQxBZscGc1bWZYF7em3NuZZB9S74a6F3bIlKNSd4c+8K2EqyBNpV/1cHSa2RwCkaER9U/bDhSOrR63ltGjErdha9REV1365RtH+80eQCBM5RKfRA3O+QfTXkk0csRO7ulpCSHuDCv3Q4k7NiCASPfkvyVHnW5IQxNaPufbCVRtSSpUMD/N+W+iPdHImEvZthp7n2s9RUW0wR8sSyvnEYP9ZFVtUOuqwbyRIDPxMM92yN0OfF2SiY2YoBK4FwWN3p1tpKPCg9gbQm2JG+ItrfurwmoiCIMr1erJIqYbs92sKHRLhiesohFnN0aaHlttsbwjDxlF98Y6/RezxhvO5X/63WFmjW8pv+rr/W5AE1oY9SzsOvW+avWqDjWSwgNV8alSAi9x6s8qBNlsoIZL+xd8t4LdN4qF5/yDsKac2YgKYfDge7l/3g1aqx4y7/Hb6MtymQL27KIRtqGnOb5lHfTdQGi1ef8o/MW2XXKMTVqq4143IZERgKlH5/3TEqaK41ALgFvusbvhyBMNSlvQDYXXiKkfZPKkMTKJL5KMT3xiA+Vg0XKzIkE2HcgEL3U="
  app: "mortgage-tool"
  env: "Mortgagetool-env-1"
  region: "eu-west-2"
  bucket_name: "mortgage-tool-source"
  zip_file: server/mortgage-tool.zip
  skip_cleanup: true