language: java
script:
- mvn assembly:assembly -DdescriptorId=jar-with-dependencies -DskipTests
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region eu-west-2)
  - docker build -t mortgage-api .
  - docker tag mortgage-api:latest public.ecr.aws/y4b5m7t6/mortgage-api:latest
  - docker push public.ecr.aws/y4b5m7t6/mortgage-api:latest
#deploy:
#  provider: elasticbeanstalk
#  app: mortgage-tool
#  env: mortgage-tool-prod-env
#  region: eu-west-2
#  bucket_name: mortgage-tool-source
#  zip_file: mortgage-tool.zip
#  skip_cleanup: true
#  access_key_id:
#    secure: ZseRfbwfdkAIturKXlw1vbKM+9dzABBi0JM661fuPnnmJ6WZPq2udxObBso5gkz77Kcz5NiwLUPg5LlUwx0oALDPnhtoO2mGl1/drVwtHBjbrut07wKeC3f4a6pUrtOikGHRLVUhA8hOfkn4jrwnUjR4Oln4qbuP1jUsKZ6Wsm9uinJ7F76lvZSQ2ubGrdwCbyF/17Gr1Wf3eolk0ujBwqzDCcEn2EJUODGv8YPqnx+lPy5KcqxA4yGhDvnZbYfX8el8xYU3o/k8ipYOoQIFFaBE6LWjLszeewH5YrNcIglk5S5eOiBM7hMtfhJSMi7f0v8muSMvRU0GWMB3XefLzzCfkBOGkBs0NSdxzAhwMad7+DIVbQk6pG/3T1jheITiWsOeqi3+pO3eSFnS60xqPoCFinERIr45JTPb1zy3wsxdJrqX1rPfuJjCn7lqYESGepaOeAKH8jKhoGx0j1rWYCZr0KLWuMsfAF/RMuPw9HjgOQjsr2/x4qyAXPPET6in4xKLsLsiyviAYa6tWAr7RsdfwFRnb8l0bgS4roSEELhs3wALdG8mnJdAHiB4LqBw0EcwlL9ay0aAHVBB66xvwZJcL+U5i9sNW+AQ7uiQhTbT1ddL4iFU/4Lz6mp5c2IvrZfSgCvDJ1ISPOxOrLG3xclatCIZKgbDm3vKm0zXM7k=
#  secret_access_key:
#    secure: HSUAvhzvSLWy4QLmA4pkMECTm1goF+mtSGuZIbmTaqWKV2o9CRq5aFM9GoIMbGGav5b7d1woLVoPH5UUl3z4TVq8QniQoss8KICnzYhQeP7KCd3QHE8Y1JtlqOZDOhX8HyNxdJxzqn49bYMLefX0YxLA2dA/8OlQioQDqDoYXoUkOkWq2M0tB2LXQpoBXMG4Z4eGnEX/SCr6Kju/kjupfx2DS7yFEOdgJFsYRCFhFkP837MkkrRf9V+XH3RmwhDr5J5UwmYo2aNHF9Vg/+jxOsaxUAyl1S7m1FIhwH2exaVuVVva4rUK89RKr6vULPcZwuw6mklz+87nl4J7CtC1L6mYvSSbpDWfmQe0cSSJ+zX1adXffPbkkkzaMzfcbq7SgYk9qEwsmeAWikug0uCC/ED1YxE4lN6ljy8yHt0IPX6o3Mz6BqW8TWbUsrs0sQ5SWF2Uxynq60iyUiXjYKFkbvITvFpe+lthsdgnET6DNvbw2+5B/FJCvg3bpCNos+E9f1BNC3M1lS2XWMJC/C0KYRguMLoZMzwTFoSl9ONSYrcyLvSE69A9+fW1BDAZUbCmarLhF4FjvD0y9QuzsuT53Xqam85Du7YTckeVkQgeU3zjymVj/tjGVzv7KFJEyU1IreYt0R5IxaR+omZL7GQ0yLyg7+2ZVDhoyvkr/pt9V/k=
